language: minimal

matrix:
  include:
    - name: "Debian 9 (Stretch)"
      os: linux
      sudo: required
      services:
        - docker
      env: 
        - CI_TYPE=deb
        - WORKSPACE=${TRAVIS_BUILD_DIR}
        - RUNNER="docker"
        - IMAGE="debian:stretch"
    
    - name: "Debian 10 (Buster)"
      os: linux
      sudo: required
      services:
        - docker
      env: 
        - CI_TYPE=deb
        - WORKSPACE=${TRAVIS_BUILD_DIR}
        - RUNNER="docker"
        - IMAGE="debian:buster"
    
    - name: "Ubuntu 18.04 (Bionic)"
      os: linux
      sudo: required
      services:
        - docker
      env: 
        - CI_TYPE=deb
        - WORKSPACE=${TRAVIS_BUILD_DIR}
        - RUNNER="docker"
        - IMAGE="ubuntu:bionic"
    
    - name: "Ubuntu 20.04 (Focal)"
      os: linux
      sudo: required
      services:
        - docker
      env: 
        - CI_TYPE=deb
        - WORKSPACE=${TRAVIS_BUILD_DIR}
        - RUNNER="docker"
        - IMAGE="ubuntu:focal"
    
    # - name: "macOS 10.14 (Mojave)"
    #   os: osx
    #   osx_image: xcode11
    #   env: 
    #     - CI_TYPE=brew 
    #     - CMAKE_OPTIONS="-DBoost_NO_BOOST_CMAKE=ON -DICU_ROOT=/usr/local/Cellar/icu4c/*"
    #     - WORKSPACE=${TRAVIS_BUILD_DIR}
    #     - RUNNER=""
    #   cache:
    #     directories:
    #       - $HOME/Library/Caches/Homebrew
    #   before_cache:
    #     - brew cleanup

script: ./.ci/run.sh
